### ISSUE TITLE
Error Code Recevied when trying to book time slot

### ISSUE THREAD

**Issue by Gulfalpha** [ryanmitchell/ti-ext-mealtimes#1]
When a customer picks a date and time then hits confirm they receive a list of error code.  We have invited several staff to test the system prior to going live with all of our customers and are ourselves using two computers to book items.  This error is happening on one of our computers, where the other one has no issue??

Currently using version 3.0.4-beta23.2

Error log contains: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Thoughtco\Menus_model' not foundin /var/www/html/extensions/thoughtco/mealtimes/Extension.php:27

Thank you.

**Comment by ryanmitchell** [comment]
Yep looks like a bug on my side.
I'll push a fix shortly and you should see it in your admin panel in an hour or so.

**Comment by Gulfalpha** [comment]
Not too sure if this is related, but the Mealtimes update V1.9 that came out last week won't clear after install.  You click on the update button and it all seems to update ok, but the update is still displayed in the update area ((1) update available).

**Comment by ryanmitchell** [comment]
Hopefully the new push will resolve that

**Comment by Gulfalpha** [comment]
Hi Ryan,  just checking that I have not missed your fix?  No worries if you haven't had time, I am just checking that its not me being dumb? Thanks

**Comment by ryanmitchell** [comment]
I released v1.10 a couple of days ago. 
If it doesn’t work let me know the exact error and how to recreate it

**Comment by Gulfalpha** [comment]
Hi Ryan, all I have is V1.9 showing and it is not disappearing.  I have now tried the ignore and remove the update but it still remains?

**Comment by Gulfalpha** [comment]
![image](https://user-images.githubusercontent.com/72857980/97434776-6a1a9000-1917-11eb-954f-3a22f6c6913f.png)

not too sure if you will be able to view this?

**Comment by ryanmitchell** [comment]
Try downloading 1.10 from the release page here and then installing by FTP

**Comment by Gulfalpha** [comment]
Thanks Ryan will try that way

**Comment by ryanmitchell** [comment]
Did this get resolved?

**Comment by Gulfalpha** [comment]
Hi Ryan, unfortunately this is still on the I.T. departments to do list.  I did have a zoom meeting with someone from I.T. who can potentially sort this out, but his work load is really big just now.  We are currently trying to recruit a coder, to replace a member of staff who initially set this up for me.   Unfortunately they are not likely to be in post until after the Christmas break.

I will give you an update as soon as I can.
