### ISSUE TITLE
Unable to Create/Modify Scheduled Menus on TI  v3.0.4-beta.25.2

### ISSUE THREAD

**Issue by shelemiah** [ryanmitchell/ti-ext-mealtimes#3]
After upgrading to TI version 3.0.4-beta.25.2 I have been unable to create/modify any Scheduled Menus using the Mealtime Extension. The following exception is produced:

The 0 field is required.
The 1 field is required.

![Screen_Capture_-mealtime](https://user-images.githubusercontent.com/71740379/102724240-3c7d1200-42dc-11eb-96e6-62e27f7fb5e6.png)

**Full Trace:**
    {"#notification":" <div\n class=\"alert alert-danger\"\n data-control=\"flash-message\"\n data-allow-dismiss=\"false\"\n role=\"alert\"\n >\n <p>The 0 field is required.<\/p>\n <p>The 1 field is required.<\/p>\n <\/div>\n ","X_IGNITER_ERROR_FIELDS":[["The 0 field is required."],["The 1 field is required."]],"X_IGNITER_ERROR_MESSAGE":"The 0 field is required."}/var/www/html/orders/app/admin/classes/AdminController.php#297Igniter\Flame\Exception\AjaxException
    #0 /var/www/html/orders/app/admin/classes/AdminController.php(167): Admin\Classes\AdminController->processHandlers()
    #1 /var/www/html/orders/app/system/classes/Controller.php(106): Admin\Classes\AdminController->remap()
    #2 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): System\Classes\Controller->runAdmin()
    #3 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
    #4 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
    #5 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
    #6 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
    #7 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
    #8 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #9 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
    #10 /var/www/html/orders/vendor/tastyigniter/flame/src/Currency/Middleware/CurrencyMiddleware.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #11 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Currency\Middleware\CurrencyMiddleware->handle()
    #12 /var/www/html/orders/app/admin/middleware/LogUserLastSeen.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #13 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Admin\Middleware\LogUserLastSeen->handle()
    #14 /var/www/html/orders/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #15 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Translation\Middleware\Localization->handle()
    #16 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #17 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle()
    #18 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #19 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
    #20 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #21 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
    #22 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #23 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
    #24 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #25 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
    #26 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #27 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
    #28 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
    #29 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
    #30 /var/www/html/orders/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute()
    #31 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch()
    #32 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
    #33 /var/www/html/orders/extensions/igniter/debugbar/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #34 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
    #35 /var/www/html/orders/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #36 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\Flame\Setting\Middleware\SaveSetting->handle()
    #37 /var/www/html/orders/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #38 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
    #39 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #40 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
    #41 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #42 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
    #43 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #44 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
    #45 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
    #46 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
    #47 /var/www/html/orders/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
    #48 /var/www/html/orders/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
    #49 {main}

**Comment by ryanmitchell** [comment]
Just pushed a new release (1.11) which should resolve this.

**Comment by shelemiah** [comment]
Your new release (1.11) resolves the issue. Thanks a million.
