### ISSUE TITLE
[Bug]: Support for Multiple Menu Schedules 

### ISSUE THREAD

**Issue by shelemiah** [ryanmitchell/ti-ext-mealtimes#4]
### What happened?

When a menu item has more than one (1) menu schedule selected it is never available regardless of the schedule. 

1. Edit a meal item configuration from the admin menu.
2. Select/enable two (2) or more menu schedules.
3. Save meal item.
4. Test to see if the menu item is available based on the select menu schedule days/time.

### What did you expect to happen?

The meal item should conform to either of the defined menu schedules selected. 

Example:
Defined menu schedules "Mon.-Menu" and "Tues-Menu" are configured to display meal items on Mondays and Tuesdays respectively. When both menu schedules are selected on a single menu item the menu items should be available on both Mondays and Tuesdays.

### Version

TI v 3.0.7 & Mealtime v1.13

### What browser are you seeing the problem on?

Firefox, Chrome

**Comment by ryanmitchell** [comment]
This is the intended behaviour. If any mealtime is not available then the menu item is not displayed. The only other option is to  hide it when all mealtimes are not available, which doesnt seem like the right approach to me.

**Comment by shelemiah** [comment]
Just to confirm as I don't believe I explained the issue correctly.

- We have two separate mealtimes "Mon.-Menu" and another "Tues.-Menu". They are to display meal items on Mondays and the other on Tuesdays.
- If I have a meal item with the mealtime "Mon.-Menu" selected only it displays perfectly for that day of the week.
- If I want to have that meal item available also on Tuesdays I usually add mealtime "Tues.-Menu" to the same item. 
![Screen_Capture_-_Sep_6__5_22_AM](https://user-images.githubusercontent.com/71740379/132203129-e012dbc4-0fad-485f-bd10-5fd4e29117f2.png)

- However, when this is done the item is no longer available on Mondays or on Tuesdays. 
![Screen_Capture_-_Sep_6__5_21_AM](https://user-images.githubusercontent.com/71740379/132203173-27ca1676-4d07-44e2-9c60-c3e7f9400fb9.png)

This seems to only occur when multiple mealtimes/menu schedules are selected.

**Comment by ryanmitchell** [comment]
Yes I understood what you meant.

If an item is in any mealtime that is not available then the item is not available, thats my intended behaviour.

**Comment by shelemiah** [comment]
Okay. Thank you.

**Comment by shelemiah** [comment]
@ryanmitchell after closing the issue I realised that the behaviour in v1.12 is different from v1.13 with regards to this use case. 

The logic in **v1.12** was:

`$mealtimeNotAvailable = true;`
`$location = Location::instance();`
`$mealtimes->each(function($mealtime) use (&$mealtimeNotAvailable, $location){`
`    if ($mealtime->isAvailableSchedule($location->orderDateTime())){`
`        $mealtimeNotAvailable = false;`
`    }`
`});`

$mealtimeNotAvailable was initialised to TRUE then tested with isAvailableSchedule and flagged as FALSE where applicable.
___________

The logic in **v1.13** is:

`$mealtimeNotAvailable = false;`
`            $model->mealtimes->each(function($mealtime) use (&$mealtimeNotAvailable, $dateTime){`
`                if (!$mealtime->isAvailableSchedule($dateTime))`
`                    $mealtimeNotAvailable = true;`
`            });`

$mealtimeNotAvailable is initialised to FALSE then tested with !isAvailableSchedule and flagged as TRUE where applicable.

The logic from v1.12 gave me more flexibility, but I understand your position on the intended behaviour.

**Comment by ryanmitchell** [comment]
Its been changed a couple of times throughout the lifetime of the extension, depending on changes to core and what made most sense.

You can easily amend the code if you want it to work differently. I'd also accept a PR for it to be a setting that would allow it to be changed per install.
