### ISSUE TITLE
[Bug]: Multiple Mealtime Schedule

### ISSUE THREAD

**Issue by shelemiah** [ryanmitchell/ti-ext-mealtimes#7]
### What happened?

When multiple mealtime schedules are selected on a meal item, the meal item is not available. 

Use Case:
A Burger that we would like available for Lunch (11:00-14:00) and Late Night (20:00-22:00). What happens is at 11:30, the Burger is not available although it should under the mealtime schedule Lunch. 

### What did you expect to happen?

The Burger should be **available** for Lunch (11:00 - 14:00)
The Burger should not be available 14:01 - 19:59
The Burger should be **available** for Late Night (20:00 - 22:00)
The Burger should not be available 22:01 - 23:59

### Version

1.14

### What browser are you seeing the problem on?

Firefox, Chrome

**Comment by ryanmitchell** [comment]
This isnt a bug, its by design. If its not available in ANY mealtime added then its not available.

**Comment by shelemiah** [comment]
Okay just wanted to confirm. As I know you mentioned the same before.

Thanks for the quick response.

**Comment by ryanmitchell** [comment]
You are welcome to open a pull request to change the behaviour
